version: 2.1

orbs:
  slack: circleci/slack@4.12.0

commands:
  init-slack:
    steps:
      - checkout
      - run:
          name: Set Message Info
          when: always
          command: |
            SLACK_TEMPLATE_SUCCESS=$(cat .circleci/template/slack-success.json)
            echo "export SLACK_TEMPLATE_SUCCESS='${SLACK_TEMPLATE_SUCCESS}'" >> $BASH_ENV
            source $BASH_ENV

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - init-slack
      - run:
          name: Run
          command: echo 'run'
      - slack/notify:
          channel: 'C049P1BNSR3'
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "1",
                      "text": "2",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - run: echo "deploy my app"
      - slack/notify:
          channel: 'C049P1BNSR3'
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: 'C049P1BNSR3'
          event: pass
          template: SLACK_TEMPLATE_SUCCESS

workflows:
  notify:
    jobs:
      - notify:
          context: SLACK_TEST
          filters:
            branches:
              only:
                - feature/environment
