version: 2.1

orbs:
  slack: circleci/slack@4.12.0

commands:
  init-slack:
    steps:
      - checkout
      - run:
          name: Set Message Info
          when: always
          command: |
            SLACK_TEMPLATE_START=$(cat .circleci/template/slack-start.json)
            SLACK_TEMPLATE_SUCCESS=$(cat .circleci/template/slack-success.json)
            SLACK_TEMPLATE_FAIL=$(cat .circleci/template/slack-fail.json)
            echo "export SLACK_TEMPLATE_START='${SLACK_TEMPLATE_START}'" >> $BASH_ENV
            echo "export SLACK_TEMPLATE_SUCCESS='${SLACK_TEMPLATE_SUCCESS}'" >> $BASH_ENV
            echo "export SLACK_TEMPLATE_FAIL='${SLACK_TEMPLATE_FAIL}'" >> $BASH_ENV
            source $BASH_ENV
  notification-start:
    steps:
      - slack/notify:
          channel: 'C049P1BNSR3'
          event: always
          template: SLACK_TEMPLATE_START
  notification-fail:
    steps:
      - slack/notify:
          channel: 'C049P1BNSR3'
          event: fail
          template: SLACK_TEMPLATE_FAIL
  notification-success:
    steps:
      - slack/notify:
          channel: 'C049P1BNSR3'
          event: pass
          template: SLACK_TEMPLATE_SUCCESS

jobs:
  notify-start:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - init-slack
      - notification-start

workflows:
  notify:
    jobs:
      - notify-start:
          context: SLACK_TEST
